### PR TITLE
Minor fix for SVGP

### PR DESCRIPTION
**Pull request by meta-inf**
A variance was mistaken as std. dev.

Note that while the result is worse after the fix, it still matches the report in the [DGP paper](https://arxiv.org/pdf/1705.08933.pdf).

### CODE REVIEW

**Comment by thjashin** [comment]
Are the results averaged over the same 20-fold validation process?

**Comment by meta-inf** [comment]
The train-test split is the same. I updated the results with repeated partitions, with 6 replicas instead of 20, but they match statistically.

**Comment by thjashin** [comment]
From my experience of the regression datasets, the results are heavily influenced by the ways of partitions. We'd better let it run for 20 and see if they are comparable.

**Comment by meta-inf** [comment]
@thjashin you're right. Results updated for Boston with 3x20 replicas. I didn't update the result for protein following the doubly stochastic VI paper, as the dataset is very large. Script:

```
for i in `seq 20`; do; python svgp.py -n_epoch=2000 -n_z=100 -lr=0.02 > /tmp/outx${i} 2>/dev/null && tail -n 1 /tmp/outx${i}; done
for i in `seq 20`; do; cat /tmp/outx${i}|tail -n 1; done|awk '{print $6, $9}'|python -c "import numpy as np; import sys; arr=np.array([list(map(float, s.split(','))) for s in sys.stdin.readlines()]); print(np.mean(arr,axis=0), np.std(arr, axis=0))"
```

**Pull request merged**
