### PR TITLE
Refactoring variational methods

### PR DESCRIPTION
**Pull request by thjashin**
The PR refactors variational methods in zhusuan based on the whitepaper draft, to enable more unified variational API that are easy-to-compose and easy-to-doc.

Variational methods are categorized by objectives.
*  Exclusive KL
    - `zs.variational.elbo()`, return `EvidenceLowerBoundObjective`
*  Monte-Carlo  objectives
    - `zs.variational.importance_weighted_objective()`, return `ImportanceWeightedObjective`
* Inclusive KL
    - `zs.variational.klpq()`, return `InclusiveKLObjective`

Different gradient estimators are provided for each objective class.
* `EvidenceLowerBoundObjective`
    - `sgvb`
    - `reinforce`
* `ImportanceWeightedObjective`
    - `sgvb` (IWAE under this situation)
    - `vimco`
* `InclusiveKLObjective`
    - `rws`

Also a first step to enhance doc strings for the variational APIs.
I'll add tests and migrate examples in the following days.

### CODE REVIEW

**Comment by thjashin** [comment]
@ssydasheng @cjf00000 Can you comment on the new API?

**Comment by ssydasheng** [comment]
it seems that whitepaper has the api for importance weighted as
`zs.iw_bound`
but in this pull request, the api for importance weighted objective is in `monte_carlo.py`, which doesn't seems very appropriate. And the api is still `importance_weighted_objective` (different from `iw_bound` and kind of long)

**Comment by thjashin** [comment]
@ssydasheng Yeah I may adapt the name in the paper a little later. Now it's a bit long but I think iw is not very clear and it's okay to stick to the longer name currently. Or any good name you can come up with?

btw, I mean if you can comment on whether the design is appropriate and any suggestions on that?

**Comment by ssydasheng** [comment]
I think attributing them by objectives is quite reasonable.

**Pull request merged**
