### PR TITLE
Added `get_shape()` 

### LINKED ISSUE #69: Issue with the shapes required in tf.layers
Following a standard VAE example for the geneative model that looks like this:

```
@zs.reuse("p")
def gen2(func, observed, bs, dim_z, n_samples):
    with zs.BayesianNet(observed=observed) as p:
        z_mean = tf.zeros([bs, dim_z])
        z = zs.Normal("z", z_mean, std=1., group_ndims=1, n_samples=n_samples)
        x_logits = func(z)
        x = zs.Bernoulli("x", x_logits, group_ndims=1)
    return p
```
where `func` just applies a bunch of dense layers from `tf.layers` I get the error:
```
Traceback (most recent call last):
  File "/opt/pycharm-2017.2.3/helpers/pydev/pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm-2017.2.3/helpers/pydev/pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/pycharm-2017.2.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/alex/work/python/eval_vi/bin/test.py", line 37, in <module>
    p = gen2(gen_func, {"z": qz_samples, "x": x_bin}, bs, dim_z, n_samples)
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 278, in __call__
    result = self._call_func(args, kwargs, check_for_new_variables=False)
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 217, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/alex/work/python/eval_vi/bb_eval_vi/models/__init__.py", line 82, in gen2
    x_logits = func(z)
  File "/home/alex/work/python/eval_vi/bb_eval_vi/models/__init__.py", line 47, in dense_stack
    return stack.apply(inputs)
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 721, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 594, in __call__
    input_shapes = nest.map_structure(lambda x: x.get_shape(), inputs)
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/util/nest.py", line 387, in map_structure
    structure[0], [func(*x) for x in entries])
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/util/nest.py", line 387, in <listcomp>
    structure[0], [func(*x) for x in entries])
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 594, in <lambda>
    input_shapes = nest.map_structure(lambda x: x.get_shape(), inputs)
AttributeError: 'Normal' object has no attribute 'get_shape'

originally defined at:
  File "/home/alex/work/python/eval_vi/bin/test.py", line 4, in <module>
    from bb_eval_vi.models import *
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/alex/work/python/eval_vi/bb_eval_vi/models/__init__.py", line 77, in <module>
    @zs.reuse("p")
  File "/home/alex/work/python/zhusuan/zhusuan/model/base.py", line 413, in <lambda>
    return lambda f: tf.make_template(scope, f)
```
Which I think is related to the fact that the model classes have no shapes. However, this makes it quite inconvinient to use like this.

### PR DESCRIPTION
**Pull request by botev**
Added `get_shape()` to `base.Distribution` for compatibility with `tf.layers`.
Closes #69

### CODE REVIEW

**Comment by thjashin** [comment]
Great, thanks! Does this work with `tf.layers`? If it works, can you add a test to confirm this?

**Comment by botev** [comment]
It does yes... where do you want me to chuck in the test for that?

**Comment by thjashin** [comment]
I feel to put it in the test of StochasticTensor is ok?

**Comment by botev** [comment]
Done.

**Pull request merged**
